/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Sistema.Colegio.Vista.Admin;

/**
 *
 * @author User
 */
public class VistaAdmin extends javax.swing.JFrame {

    /**
     * Creates new form VistaAdmin
     */
    public VistaAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtonReporteNotas = new javax.swing.JButton();
        jButtonMatricular = new javax.swing.JButton();
        jButtonCrearDocente = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButtonHorarios = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Palatino Linotype", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("BIENVENIDO ADMINISTRADOR");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, -1, 47));

        jButtonReporteNotas.setBackground(new java.awt.Color(255, 255, 204));
        jButtonReporteNotas.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jButtonReporteNotas.setForeground(new java.awt.Color(0, 0, 0));
        jButtonReporteNotas.setText("REPORTE NOTAS");
        jButtonReporteNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReporteNotasActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonReporteNotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 210, 210, 410));

        jButtonMatricular.setBackground(new java.awt.Color(255, 255, 204));
        jButtonMatricular.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jButtonMatricular.setForeground(new java.awt.Color(0, 0, 0));
        jButtonMatricular.setText("MATRICULAS");
        jButtonMatricular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMatricularActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonMatricular, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 210, 410));

        jButtonCrearDocente.setBackground(new java.awt.Color(255, 255, 204));
        jButtonCrearDocente.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jButtonCrearDocente.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCrearDocente.setText("CREAR DOCENTE");
        jButtonCrearDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearDocenteActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCrearDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 210, 410));

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 610, 70));

        jButtonHorarios.setBackground(new java.awt.Color(255, 255, 204));
        jButtonHorarios.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jButtonHorarios.setForeground(new java.awt.Color(0, 0, 0));
        jButtonHorarios.setText("HORARIOS");
        jButtonHorarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHorariosActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonHorarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 210, 210, 410));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonReporteNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReporteNotasActionPerformed
        VistaNotasAlumnos vn = new VistaNotasAlumnos();
        vn.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonReporteNotasActionPerformed

    private void jButtonMatricularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMatricularActionPerformed
    VistaMatricula vm = new VistaMatricula();
    vm.setVisible(true);
    dispose(); 

    }//GEN-LAST:event_jButtonMatricularActionPerformed

    private void jButtonCrearDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearDocenteActionPerformed
    VistaCrearDocente vd = new VistaCrearDocente();
    vd.setVisible(true);
    dispose();


    }//GEN-LAST:event_jButtonCrearDocenteActionPerformed

    private void jButtonHorariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHorariosActionPerformed
        VistaHorarios vh = new VistaHorarios();
        vh.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonHorariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        VistaAdmin va = new VistaAdmin();
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCrearDocente;
    private javax.swing.JButton jButtonHorarios;
    private javax.swing.JButton jButtonMatricular;
    private javax.swing.JButton jButtonReporteNotas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
